[package]
name = "test-routine01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
futures = "0.3.25"
tokio = { version = "1.20.1", features = ["full"] }
